# -*- coding: utf-8 -*-
"""PGM Inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cPe4kWPUnwh4q73xFm-vPST4--wFciC
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pgmpy.models import BayesianModel
from pgmpy.estimators import HillClimbSearch, BicScore, K2Score
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination, BeliefPropagation
import pickle
import logging
import networkx as nx

column = 'Fracture'
filename = "_".join([w for w in column.split(" ")])
with open('bayes_'+filename.lower()+'_model.pkl','rb') as f:
    model = pickle.load(f)

inference = VariableElimination(model)
pred = inference.query(variables = [("labels",1)],evidence={'Sex':0,'Age':17})

print(pred)

